when:
  - branch: main
    event: [cron, manual]
    name: "Update Submodules"
  

steps:
    setup:
        image: alpine/git
        commands:
            - git config user.name "woodpecker-ci"
            - git config user.email "ci@ci.ujol.dev"

    checkout:
        image: alpine/git
        commands:
            - git clone --recursive $CI_REPO_NAME .
            - git fetch origin
            - git reset --hard origin/main
            - git submodule update --remote --recursive

    update_submodules:
        image: alpine/git
        commands: |
            if [ -n "$(git status -s)" ]; then
              git add .;
              git commit -m "Update submodules to the latest commit";
              MAX_RETRIES=5;
              RETRY_COUNT=0;
              while ! git push && [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
                git fetch origin;
                git rebase origin/main;
                RETRY_COUNT=$((RETRY_COUNT+1));
                echo "Push failed. Retrying... (Attempt $RETRY_COUNT of $MAX_RETRIES)";
              done;
              if [ $RETRY_COUNT -eq $MAX_RETRIES ]; then
                echo "Failed to push after $MAX_RETRIES attempts.";
                exit 1;
              fi;
            else
              echo "No changes to commit";
            fi
