name: Push to repo branch

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
              with:
                  submodules: recursive

            - name: Install bun
              uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2.0.2
              with:
                  bun-version: latest

            - name: Install dependencies
              run: bun install

            - name: Build project
              run: bun run build

            - name: Push dist to repo branch
              uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # v4.0.0
              if: github.ref == 'refs/heads/main'
              with:
                  personal_token: ${{ secrets.GH_PAT }}
                  publish_dir: ./dist
                  publish_branch: repo
